//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.173.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace ReportingMultiSelect.UIModel
{

/// <summary>
/// Represents the UI model for the 'Example Data List' data form
/// </summary>
[global::Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModelMetadata("a3652731-baaa-496a-89f9-f0efe68cdba6")]
public partial class @ExampleDataListUIModel : global::Blackbaud.AppFx.UIModeling.Core.DataListFilterUIModel
{

#region "Enums"

    /// <summary>
    /// Enumerated values for use with the TRANSACTIONTYPESSELECTOR property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public enum TRANSACTIONTYPESSELECTORS : int
	{
        @AllTransactionTypes = 0,
        @SelectedTransactionTypes = 1
	}

    /// <summary>
    /// Enumerated values for use with the APPLICATIONSSELECTOR property
    /// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public enum APPLICATIONSSELECTORS : int
	{
        @AllApplications = 0,
        @SelectedApplications = 1
	}

#endregion

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.StringField _transactiontypes;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<TRANSACTIONTYPESSELECTORS> _transactiontypesselector;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _applications;
    private global::Blackbaud.AppFx.UIModeling.Core.ValueListField<APPLICATIONSSELECTORS> _applicationsselector;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction _showtransactiontypesform;
    private global::Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction _showapplicationsform;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public @ExampleDataListUIModel() : base()
	{


        _transactiontypes = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _transactiontypesselector = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<TRANSACTIONTYPESSELECTORS>();
        _applications = new global::Blackbaud.AppFx.UIModeling.Core.StringField();
        _applicationsselector = new global::Blackbaud.AppFx.UIModeling.Core.ValueListField<APPLICATIONSSELECTORS>();
        _showtransactiontypesform = new global::Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction();
        _showapplicationsform = new global::Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction();

        this.DataListId = new System.Guid("a3652731-baaa-496a-89f9-f0efe68cdba6");
        this.UserInterfaceUrl = "browser/htmlforms/custom/reportingmultiselect/ExampleDataList.html";

        //
        //_transactiontypes
        //
        _transactiontypes.Name = "TRANSACTIONTYPES";
        _transactiontypes.Caption = "Transaction types";
        _transactiontypes.AvailableToClient = false;
        this.Fields.Add(_transactiontypes);
        //
        //_transactiontypesselector
        //
        _transactiontypesselector.Name = "TRANSACTIONTYPESSELECTOR";
        _transactiontypesselector.Caption = "Transaction types";
        _transactiontypesselector.Required = true;
        _transactiontypesselector.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<TRANSACTIONTYPESSELECTORS> {Value = TRANSACTIONTYPESSELECTORS.@AllTransactionTypes, Translation = "All transaction types"});
        _transactiontypesselector.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<TRANSACTIONTYPESSELECTORS> {Value = TRANSACTIONTYPESSELECTORS.@SelectedTransactionTypes, Translation = "Selected transaction types"});
        _transactiontypesselector.Value = TRANSACTIONTYPESSELECTORS.@AllTransactionTypes;
        this.Fields.Add(_transactiontypesselector);
        //
        //_applications
        //
        _applications.Name = "APPLICATIONS";
        _applications.Caption = "Applications";
        _applications.AvailableToClient = false;
        this.Fields.Add(_applications);
        //
        //_applicationsselector
        //
        _applicationsselector.Name = "APPLICATIONSSELECTOR";
        _applicationsselector.Caption = "Applications";
        _applicationsselector.Required = true;
        _applicationsselector.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<APPLICATIONSSELECTORS> {Value = APPLICATIONSSELECTORS.@AllApplications, Translation = "All applications"});
        _applicationsselector.DataSource.Add(new global::Blackbaud.AppFx.UIModeling.Core.ValueListItem<APPLICATIONSSELECTORS> {Value = APPLICATIONSSELECTORS.@SelectedApplications, Translation = "Selected applications"});
        _applicationsselector.Value = APPLICATIONSSELECTORS.@AllApplications;
        this.Fields.Add(_applicationsselector);
        //
        //_showtransactiontypesform
        //
        _showtransactiontypesform.Name = "SHOWTRANSACTIONTYPESFORM";
        _showapplicationsform.Enabled = false;
        _showtransactiontypesform.Caption = "";
        _showtransactiontypesform.ImageKey = "res:editsmall";
        _showtransactiontypesform.ModelAssemblyName = "ReportingMultiSelect.UIModel.dll";
        _showtransactiontypesform.ModelClassName = "ReportingMultiSelect.UIModel.MultiSelectTransactionTypesUIModel";
        _transactiontypesselector.LinkedActions.Add(_showtransactiontypesform);
        this.Actions.Add(_showtransactiontypesform);
        //
        //_showapplicationsform
        //
        _showapplicationsform.Name = "SHOWAPPLICATIONSFORM";
        _showapplicationsform.Enabled = false;
        _showapplicationsform.Caption = "";
        _showapplicationsform.ImageKey = "res:editsmall";
        _showapplicationsform.ModelAssemblyName = "ReportingMultiSelect.UIModel.dll";
        _showapplicationsform.ModelClassName = "ReportingMultiSelect.UIModel.MultiSelectApplicationsUIModel";
        _applicationsselector.LinkedActions.Add(_showapplicationsform);
        this.Actions.Add(_showapplicationsform);

		OnCreated();

	}

    /// <summary>
    /// Transaction types
    /// </summary>
    [System.ComponentModel.Description("Transaction types")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @TRANSACTIONTYPES {
		get { return _transactiontypes; }
	}

    /// <summary>
    /// Transaction types
    /// </summary>
    [System.ComponentModel.Description("Transaction types")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<TRANSACTIONTYPESSELECTORS> @TRANSACTIONTYPESSELECTOR {
		get { return _transactiontypesselector; }
	}

    /// <summary>
    /// Applications
    /// </summary>
    [System.ComponentModel.Description("Applications")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.StringField @APPLICATIONS {
		get { return _applications; }
	}

    /// <summary>
    /// Applications
    /// </summary>
    [System.ComponentModel.Description("Applications")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ValueListField<APPLICATIONSSELECTORS> @APPLICATIONSSELECTOR {
		get { return _applicationsselector; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction @SHOWTRANSACTIONTYPESFORM {
		get { return _showtransactiontypesform; }
	}

    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.ShowCustomFormUIAction @SHOWAPPLICATIONSFORM {
		get { return _showapplicationsform; }
	}

}

}
