//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by BBUIModelLibrary
//     Version:  4.0.173.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;
using Blackbaud.AppFx.UIModeling.Core;
namespace ReportingMultiSelect.UIModel
{

/// <summary>
/// Represents the UI model for the 'Multi Select Transaction Types' data form
/// </summary>
public partial class MultiSelectTransactionTypesUIModel : global::Blackbaud.AppFx.UIModeling.Core.CustomUIModel
{

#region "Extensibility methods"

	partial void OnCreated();

#endregion

    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _payment;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _pledge;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _recurringgift;
    private global::Blackbaud.AppFx.UIModeling.Core.BooleanField _matchinggift;
    private global::Blackbaud.AppFx.UIModeling.Core.StringField _transactiontypesdelimited;
    private global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction _selectall;
    private global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction _unselectall;
    private global::System.Collections.Generic.List<BooleanField> _transactionTypes;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public MultiSelectTransactionTypesUIModel() : base()
	{


        _payment = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _pledge = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _recurringgift = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _matchinggift = new global::Blackbaud.AppFx.UIModeling.Core.BooleanField();
        _selectall = new global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction();
        _unselectall = new global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction();
        _transactionTypes = new global::System.Collections.Generic.List<BooleanField>();
        _transactiontypesdelimited = new global::Blackbaud.AppFx.UIModeling.Core.StringField();

        this.FORMHEADER.Value = "Select transaction types";
        this.UserInterfaceUrl = "browser/htmlforms/custom/reportingmultiselect/MultiSelectTransactionTypes.html";
        //
        // _transactiontypesdelimited
        //
        _transactiontypesdelimited.Name = "TRANSACTIONTYPESDELIMITED";
        this.Fields.Add(_transactiontypesdelimited);
        //
        //_payment
        //
        _payment.Name = "PAYMENT";
        _payment.Caption = "Payment";
        this.Fields.Add(_payment);
        //
        //_pledge
        //
        _pledge.Name = "PLEDGE";
        _pledge.Caption = "Pledge";
        this.Fields.Add(_pledge);
        //
        //_recurringgift
        //
        _recurringgift.Name = "RECURRINGGIFT";
        _recurringgift.Caption = "Recurring gift";
        this.Fields.Add(_recurringgift);
        //
        //_matchinggift
        //
        _matchinggift.Name = "MATCHINGGIFT";
        _matchinggift.Caption = "Matching gift claim";        
        this.Fields.Add(_matchinggift);
        //
        //_selectall
        //
        _selectall.Name = "SELECTALL";
        _selectall.Caption = "Select all";
        this.Actions.Add(_selectall);
        //
        //_unselectall
        //
        _unselectall.Name = "UNSELECTALL";
        _unselectall.Caption = "Unselect all";
        this.Actions.Add(_unselectall);        
        
        _transactionTypes.Add(this._payment);
        _transactionTypes.Add(this._pledge);
        _transactionTypes.Add(this._recurringgift);
        _transactionTypes.Add(this._matchinggift);

		OnCreated();

	}
    /// <summary>
    /// TransactionTypesDelimited
    /// </summary>
    [System.ComponentModel.Description("Payment")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
    public global::Blackbaud.AppFx.UIModeling.Core.StringField @TRANSACTIONTYPESDELIMITED
    {
        get { return _transactiontypesdelimited; }
    }

    /// <summary>
    /// Payment
    /// </summary>
    [System.ComponentModel.Description("Payment")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @PAYMENT {
		get { return _payment; }
	}

    /// <summary>
    /// Pledge
    /// </summary>
    [System.ComponentModel.Description("Pledge")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @PLEDGE {
		get { return _pledge; }
	}

    /// <summary>
    /// RecurringGift
    /// </summary>
    [System.ComponentModel.Description("RecurringGift")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @RECURRINGGIFT {
		get { return _recurringgift; }
	}

    /// <summary>
    /// MatchingGift
    /// </summary>
    [System.ComponentModel.Description("MatchingGift")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.BooleanField @MATCHINGGIFT {
		get { return _matchinggift; }
	}

    /// <summary>
    /// Select all
    /// </summary>
    [System.ComponentModel.Description("Select all")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction @SELECTALL {
		get { return _selectall; }
	}

    /// <summary>
    /// Unselect all
    /// </summary>
    [System.ComponentModel.Description("Unselect all")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
	public global::Blackbaud.AppFx.UIModeling.Core.GenericUIAction @UNSELECTALL {
		get { return _unselectall; }
	}

    /// <summary>
    /// Pledge
    /// </summary>
    [System.ComponentModel.Description("Pledge")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "4.0.173.0")]
    public global::System.Collections.Generic.List<BooleanField> @TRANSACTIONTYPES
    {
        get { return _transactionTypes; }
    }

}

}
